<option 
  value="fonticon-bicycle"
  data-icon="fonticon-bicycle"
>bicycle</option>
<option 
  value="fonticon-delivery"
  data-icon="fonticon-delivery"
>delivery</option>
<option 
  value="fonticon-bookmark"
  data-icon="fonticon-bookmark"
>bookmark</option>
<option 
  value="fonticon-like"
  data-icon="fonticon-like"
>like</option>
<option 
  value="fonticon-microphone"
  data-icon="fonticon-microphone"
>microphone</option>
<option 
  value="fonticon-location"
  data-icon="fonticon-location"
>location</option>
<option 
  value="fonticon-gallery"
  data-icon="fonticon-gallery"
>gallery</option>
<option 
  value="fonticon-share"
  data-icon="fonticon-share"
>share</option>
<option 
  value="fonticon-star"
  data-icon="fonticon-star"
>star</option>
<option 
  value="fonticon-trash"
  data-icon="fonticon-trash"
>trash</option>
<option 
  value="fonticon-user"
  data-icon="fonticon-user"
>user</option>
<option 
  value="fonticon-view"
  data-icon="fonticon-view"
>view</option>
<option 
  value="fonticon-user-2"
  data-icon="fonticon-user-2"
>user-2</option>
<option 
  value="fonticon-pin"
  data-icon="fonticon-pin"
>pin</option>
<option 
  value="fonticon-chat"
  data-icon="fonticon-chat"
>chat</option>
<option 
  value="fonticon-home"
  data-icon="fonticon-home"
>home</option>
<option 
  value="fonticon-mail"
  data-icon="fonticon-mail"
>mail</option>
<option 
  value="fonticon-settings"
  data-icon="fonticon-settings"
>settings</option>
<option 
  value="fonticon-settings"
  data-icon="fonticon-settings"
>settings</option>
<option 
  value="fonticon-link"
  data-icon="fonticon-link"
>link</option>
<option 
  value="fonticon-attach"
  data-icon="fonticon-attach"
>attach</option>
<option 
  value="fonticon-smile"
  data-icon="fonticon-smile"
>smile</option>
<option 
  value="fonticon-moon"
  data-icon="fonticon-moon"
>moon</option>
<option 
  value="fonticon-sun"
  data-icon="fonticon-sun"
>sun</option>
<option 
  value="fonticon-train"
  data-icon="fonticon-train"
>train</option>
<option 
  value="fonticon-eclipse"
  data-icon="fonticon-eclipse"
>eclipse</option>
<option 
  value="fonticon-drone"
  data-icon="fonticon-drone"
>drone</option>
<option 
  value="fonticon-truck"
  data-icon="fonticon-truck"
>truck</option>
<option 
  value="fonticon-ship"
  data-icon="fonticon-ship"
>ship</option>
<option 
  value="fonticon-offline"
  data-icon="fonticon-offline"
>offline</option>